### ISSUE TITLE
Question:  How to join a cluster with a "hidden" node

### ISSUE THREAD

**Issue by cjimison** [Kyorai/riak_core#37]
This is more of a general riak_core question and any guidance would be GREATLY appreciated.

I would like to create a 4 node cluster.

Nodes A, B, and C would be some kind of riak_core cluster with a series of "services" running (example would be the TanoDB from the little riak core book).  Node D would be a node that says runs some kind of front end like Cowboy.

How can I have Node D call ":riak_core.join" without actually running any VNodes?  While I could not call "join" in the riak core cluster and just RPC the request to one of the nodes, I would love to have Node D have a copy of at least the ring so I know which node is running the primary VNode (or a fallback if it is down) and send a request directly to it.

Thanks!

**Comment by jadeallenx** [comment]
The whole point of riak is to distribute your service requests around the ring. As a client of Riak you should not care (and I argue not know) what server is the primary and fallback, etc.  All of that bookkeeping should be handled by riak_core itself.  All you need to do is expose some kind of stateless HTTP API layer that calls into your riak cluster using riak_client.

**Comment by cjimison** [comment]
Hi Mark,

Thank you for responding with your insights and I apologize if my use case may have sounded a bit watered down.  In the above use case, I agree that for a normal web service this would be a very acceptable solution.  However we build game servers and are very latency sensitive.  One issue we have encountered on different cloud providers are large (or I should say large for us) spikes of time when moving the messages between nodes depending on the instance type (preemptable nodes like the AWS T2 series) and network features enabled.  One easy win for us is to help "guide" the message to the correct node to reduce the number of hops it will have to make.  Especially since we don't use riak_core as just a KV system.

Setting aside the validity of my previous use case, *can* this be done? Please forgive me if this sounds petulant in any way, I really do appreciate the help.  

P.S.

I never considered using riak_client as a way to communicate to my own internal nodes.  Is this an out of the box feature of riak_core or would I need to move code from riak_kv to handle these requests?

**Comment by jadeallenx** [comment]
If you're not using riak_client what are you using to communicate with Riak? HTTP requests?

**Comment by cjimison** [comment]
I am not running Riak the database, I have just integrated riak_core into my application.  I would like to add a node to my cluster that is not responsible for running any VNodes but can route a message to a VNode.

**Comment by jadeallenx** [comment]
Ah, I see. I'm sorry I didn't understand that very well. 

I suppose it would be possible to export the ring data from any one of the cluster members periodically - and then have an independent service use the ring data to compute preflists for any given hash value on the ring.

**Comment by gpad** [comment]
@cjimison One possible solution is to have some nodes with some services and other nodes with other service. In this way you could use this service to select the node. I did something similar in a project but clearly we should get more details of the context.

**Comment by cjimison** [comment]
@gpad I was able to do just that and everything is working well.  The key piece I was missing was you still need to register the service via ```:riak_core.register``` but not call ```:riak_core.service_up``` (as you suggested in another thread).  Otherwise when you join the cluster the hand-offs will never complete.  Thanks all!
